# Data Extraction and Basic EDA
## Problem statement (tentative): Recommending movies to user's based on their preferences using prediction models in Machine Learning.

### Preferences: genre, age, year released, ratings, movie cast, language etc

### Imports

In [1]:
pip install tmdb-python

Requirement already satisfied: tmdb-python in c:\users\jovan\anaconda3\lib\site-packages (0.0.9)
Requirement already satisfied: aiohttp in c:\users\jovan\anaconda3\lib\site-packages (from tmdb-python) (3.8.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (1.3.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (21.4.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (2.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\jovan\anaconda3\lib\site-packages (from aiohttp->tmdb-python) (4.0.2)
Requirement already satisfied: idna>=2.0 in c:\users\jovan\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->tmdb-python) (3.3)
Note: you may need to restart the kernel to use updated packages.

In [30]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

# For API usage
import requests as r

### Figuring out how to import the database

In [28]:
API_KEY = "7884759e98354ed855458b12c5c2bcdc"

resp = r.get(f"https://api.themoviedb.org/3/discover/movie?api_key={API_KEY}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_watch_monetization_types=flatrate")
total_pages = resp.json()['total_pages']
cols = ['title', 'id', 'popularity', 'vote_count', 'vote_average', 'release_date', 'original_language'] #check if 'release date' is needed
data = pd.DataFrame(resp.json()['results'])[cols]

In [29]:
data.info()
data.head(n=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              20 non-null     object
 1   id                 20 non-null     int64
 2   popularity         20 non-null     float64
 3   vote_count         20 non-null     int64
 4   vote_average       20 non-null     float64
 5   release_date       20 non-null     object
 6   original_language  20 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

,title,id,popularity,vote_count,vote_average,release_date,original_language
0,Puss in Boots: The Last Wish,315162,1972.345,4613,8.4,2022-12-07,en
1,Prizefighter: The Life of Jem Belcher,943822,2522.636,38,6.8,2022-06-30,en
2,The Whale,785084,2029.776,1224,8.0,2022-12-09,en
3,Black Panther: Wakanda Forever,505642,1798.789,4097,7.3,2022-11-09,en
4,Knock at the Cabin,631842,1631.885,1010,6.4,2023-02-01,en
5,Die Hart,1077280,1398.005,180,6.2,2023-02-22,en
6,Shark Side of the Moon,1011679,1383.229,89,5.3,2022-08-12,en
7,Everything Everywhere All at Once,545611,1335.103,3727,7.9,2022-03-24,en
8,Plane,646389,1204.689,881,6.9,2023-01-12,en
9,Creed III,677179,1118.721,339,7.0,2023-03-01,en
10,Avatar: The Way of Water,76600,956.637,5748,7.7,2022-12-14,en
11,Scream VI,934433,821.579,237,7.5,2023-03-08,en
12,Little Dixie,1058949,918.963,77,6.0,2023-02-03,en
13,M3GAN,536554,843.959,2048,7.4,2022-12-28,en
14,Bandit,842942,819.926,123,6.1,2022-09-23,en
15,A Man Called Otto,937278,732.514,736,7.9,2022-12-28,en
16,Diabolik - Ginko Attacks,823999,774.758,103,5.6,2022-11-17,it
17,Lord of the Streets,965839,776.661,44,5.4,2022-04-22,en
18,Ant-Man and the Wasp: Quantumania,640146,758.067,1017,6.4,2023-02-15,en
19,Shotgun Wedding,758009,742.959,650,6.3,2022-12-28,en